version: '3.8'

services:
  
  permission-app:
    build:
      context: ..
      dockerfile: ./PermissionApp/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sql-server
      - kafka
#    networks:
#      - my-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=permissiondb;User Id=sa;Password=3mlq5nXG86eL3nF;TrustServerCertificate=true
      - KafkaConfig=kafka:9092
      - Logging__LogLevel__Default=Debug
    
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 3mlq5nXG86eL3nF
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
#    networks:
#      - my-network
        
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
#    networks:
#      - my-network
      
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - my-network
  
  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
#    networks:
#      - my-network
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic permission-history
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic test-topic
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
  
  kafka-explorer:
    image: qvantel/kafka-explorer:0.9.3
    depends_on:
      - kafka
    ports:
      - 5000:5000
    environment:
      KAFKA_BOOTSTRAP_BROKERS: kafka:9092
#    networks:
#      - my-network    
#      
#networks:
#  my-network:
#    driver: bridge