version: '3.8'

services:
  
  permission-app:
    build:
      context: ..
      dockerfile: ./PermissionApp/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sql-server
      - kafka
    environment:
      - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=permissiondb;User Id=sa;Password=3mlq5nXG86eL3nF;TrustServerCertificate=true
      - KafkaConfig=kafka:9092
      - ElasticsearchConfig=http://elasticsearch:9200
      - Logging__LogLevel__Default=Debug
    
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 3mlq5nXG86eL3nF
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
        
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
      
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic permission-history
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic test-topic
      
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "

  kafkacat:
    image: edenhill/kcat:1.7.0
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # 
      sleep 10s
      kcat -b kafka:9092 -C -t permission-history -f '\nValue (%S bytes): %s\n\Partition: %p\tOffset: %o\n--\n'     
      "
      
volumes:
  elasticsearch-data:
    driver: local